### ISSUE TITLE
This does not work

### ISSUE THREAD

**Issue by kingsleyh** [devops-recipes/provision-ecs-cluster-terraform#1]
I tried to follow the tutorial here: http://blog.shippable.com/create-a-container-cluster-using-terraform-with-aws-part-1

However after part 1 - terraform plan fails with many errors. So I tried instead to clone this repo - but again it terraform plan fails with many errors

```bash
>terraform plan

Warning: aws_iam_instance_profile.ecs-instance-profile: "roles": [DEPRECATED] Use `role` instead. Only a single role can be passed to an IAM Instance Profile



Error: aws_autoscaling_group.ecs-autoscaling-group: desired_capacity: cannot parse '' as int: strconv.ParseInt: parsing "$DESIRED_CAPACITY": invalid syntax



Error: aws_autoscaling_group.ecs-autoscaling-group: max_size: cannot parse '' as int: strconv.ParseInt: parsing "$MAX_INSTANCE_SIZE": invalid syntax



Error: aws_autoscaling_group.ecs-autoscaling-group: min_size: cannot parse '' as int: strconv.ParseInt: parsing "$MIN_INSTANCE_SIZE": invalid syntax



Error: aws_security_group.test_public_sg: "ingress.3.cidr_blocks.0" must contain a valid CIDR, got error parsing: invalid CIDR address: $TEST_PUBLIC_01_CIDR



Error: aws_security_group.test_public_sg: "ingress.3.cidr_blocks.1" must contain a valid CIDR, got error parsing: invalid CIDR address: $TEST_PUBLIC_02_CIDR



Error: aws_vpc.test_vpc: "cidr_block" must contain a valid CIDR, got error parsing: invalid CIDR address: $TEST_NETWORK_CIDR
```

**Comment by a-murphy** [comment]
Since all of the errors appear to be with the values set through environment variables, it's likely that the `pect_net_conf` `params` resource was missing.  This repository was intended to be added as a [syncRepo](http://docs.shippable.com/platform/tutorial/workflow/add-assembly-line/) in Shippable, which would have created resources for a Shippable Assembly Line, including the `params` resource.

Current documentation to create an Amazon ECS cluster with Terraform on Shippable is available [here](http://docs.shippable.com/provision/tutorial/provision-aws-ecs-terraform/).  The environment variables will need to be be hard-coded to run locally.

For any issues with Shippable in the future, please open the issue in https://github.com/Shippable/support, which is more closely monitored.
